#!/bin/sh

. packages/meta

rm -rf target/$PKG_VERSION.$PKG_REV/

mkdir build

cp -rf $PKG_NAME build/$PKG_NAME

rm -f build/$PKG_NAME/resources/.gitignore

for i in $PKG_DEPENDS;do
 mkpkg/mkpkg_$i
done

mkdir -p target/$PKG_VERSION.$PKG_REV/
cd build
zip -rq9 ../target/$PKG_VERSION.$PKG_REV/$PKG_NAME-$PKG_VERSION.$PKG_REV.zip $PKG_NAME
cp $PKG_NAME/changelog.txt ../target/$PKG_VERSION.$PKG_REV/changelog-$PKG_VERSION.$PKG_REV.txt
cp $PKG_NAME/addon.xml ../target/$PKG_VERSION.$PKG_REV/addon.xml
cd ..
rm -rf build
