#!/bin/sh

. packages/nzbToMedia/meta
cd mkpkg

echo "building $PKG_NAME..."
echo "getting sources..."
  if [ ! -d build.$PKG_NAME.git ]; then
    git clone $PKG_SITE.git build.$PKG_NAME.git
    if [ "$?" = "1" ]; then
      echo "error cloning source: $1";exit 1
    fi
  fi

  cd build.$PKG_NAME.git
    git checkout master
    git pull
    git checkout $PKG_VERSION
    if [ "$?" = "1" ]; then
      echo "error checking out $PKG_VERSION: $1";exit 1
    fi
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$GIT_REV
  cp -R build.$PKG_NAME.git $PKG_NAME-$GIT_REV
  cp -R patches/distutils $PKG_NAME-$GIT_REV/libs

for i in patches/$PKG_NAME-*.patch; do
  if [ -f "$i" ]; then
    echo "patching sources..."
    echo $i
    cat $i | patch -p1 -d `echo "$PKG_NAME-$GIT_REV" | cut -f1 -d\ `
    if [ "$?" = "1" ]; then
      echo "error patching source: $1";exit 1
    fi
  fi
done

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/.git* $PKG_NAME-$GIT_REV/*.md $PKG_NAME-$GIT_REV/*.txt $PKG_NAME-$GIT_REV/nzbToGamez.py $PKG_NAME-$GIT_REV/nzbToMylar.py $PKG_NAME-$GIT_REV/nzbToNzbDrone.py $PKG_NAME-$GIT_REV/.git* $PKG_NAME-$GIT_REV/getffmpeg.sh $PKG_NAME-$GIT_REV/core/extractor/bin/

echo "moving sources..."
  mv $PKG_NAME-$GIT_REV ../build/script.service.audo/resources/$PKG_NAME
  if [ "$?" = "1" ]; then
    echo "error building $PKG_NAME: $1";exit 1
  fi

echo "done"
exit 0
